### ISSUE TITLE
Remove .gitkeep files and mention self-explanatory alternative?

### ISSUE THREAD

**Issue by katrinleinweber** [caltechlibrary/git-desktop#8]
I suggested a change over in https://github.com/swcarpentry/git-novice/pull/571/files#diff-3c9b1b2841b52dffd10441f1fcf62f8e that is relevant here as well. Shall we apply it here?

**Comment by katrinleinweber** [comment]
Better to discuss this upstream.

**Comment by tmorrell** [comment]
Sounds good to me - PR away!
